version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: ${DOCKERHUB_USER:-local}/three-tier-api:${BUILD_TAG:-latest}
    container_name: api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
    ports:
      - "5000:5000"

  frontend:
    image: ${DOCKERHUB_USER:-local}/three-tier-frontend:${BUILD_TAG:-latest}
    container_name: frontend
    depends_on:
      - api
    ports:
      - "80:80"

volumes:
  db_data:
